### PR TITLE
Refactor systematic effects

### PR DESCRIPTION
**Pull request by victor-estrade**
Refactor systematic effects to make it cleaner
V4_* constructors and update_* functions will be used by all systematic effect
add tau_energy_scale
add jet_energy_scale
add lep_energy_scale
I left the former transform() function to avoid breaking retro compatibility
Everything seems fine BUT I still need to test those *_energy_scale function and validate their output. Especially the Missing ET computation.

### CODE REVIEW

**Comment by victor-estrade** [comment]
Allright I finished to test and validate this code.
Output is slightly different for tau energy scale because I simplified one computation (removed a useless multiply by scale then divide by scale).
I re-read formulas for Jet energy scale and Lep energy scale and everything seems fine.

I'll work on "soft term" systematic but it will better if it is another pull request.

Did not try to run the complete pipeline yet.

**Comment by victor-estrade** [comment]
[Just a reminder]
Remaining changes (maybe better in separated pull request) to do :
- In higgs_example.py the transform() method should use the new *_energy_scale() functions from higgs_four_vector module
-  In higgs_example.py add jet_energy_sc and lep_energy_sc to the existing tau_energy nuisance parameter.
- Add soft_term systematic effect to higgs_four_vector and do similar changes in higgs_example
- Allow PRI_jet_num as an input feature (cast it into float) in higgs_example

**Comment by victor-estrade** [comment]
soft_term is not working for now.
The tf.random.normal operator require to know the shape of the tensor
`ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, ?)`

**Comment by victor-estrade** [comment]
Now the 4 new systematics are implemented and their output matches the expected output.
Remaining work:
- update the higgs_example.HiggsExample class to use the new systematics
- Check that the pipeline is not broken and that we can still train models
- Allow PRI_jet_num as an input feature (cast it into float) in higgs_example.HiggsExample class

**Comment by pablodecm** [comment]
Hi @victor-estrade, can this be merged without breaking anything?

**Pull request merged**
